
# File: .github/workflows/repo-sync.yml
name: sync-gossh520-repo
on:
  schedule:
    - cron: '30 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-gossh520-repo
jobs:
  repo-sync:
    env:

      PAT: ${{ secrets.PAT }} 

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync-gossh520-repo
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/gossh520/jd_scripts.git"  
          # fallback: https://github.com/chinnkarahoi/jd_scripts.git
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
