
# File: .github/workflows/repo-sync.yml
name: sync-update-repo
on:
  schedule:
    - cron: '30 1,4,12 * * *'
  workflow_dispatch:
  watch:
    types: started

  repository_dispatch:
    types: sync-JDDJ-repo
jobs:
  repo-sync:
    env:

      PAT: ${{ secrets.PAT }} 

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync-update-repo
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/gitupdate/updateTeam.git"  
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
